#!/bin/bash

rm *.class; javac -cp ../apache-commons/commons-math3-3.3/commons-math3-3.3.jar:../Couchbase-Java-Client-1.4.6/spymemcached-2.11.5.jar:../Couchbase-Java-Client-1.4.6/couchbase-client-1.4.6.jar:../Couchbase-Java-Client-1.4.6/*:. SDK14HelloCouchbase.java 
