#!/bin/bash

rm *.class; javac -cp ../apache-commons/commons-math3-3.3/commons-math3-3.3.jar:../Couchbase-Java-Client-2.0.1/couchbase-java-client-2.0.1.jar:../Couchbase-Java-Client-2.0.1/couchbase-core-io-1.0.1.jar:../Couchbase-Java-Client-2.0.1/rxjava-1.0.0-rc.9.jar RetryWithDelay.java HelloCouchbase.java 2>&1 
