#!/bin/bash

java -cp ../apache-commons/commons-math3-3.3/commons-math3-3.3.jar:../Couchbase-Java-Client-2.0.1/couchbase-java-client-2.0.1.jar:../Couchbase-Java-Client-2.0.1/couchbase-core-io-1.0.1.jar:../Couchbase-Java-Client-2.0.1/rxjava-1.0.0-rc.9.jar:.  HelloCouchbase 2>&1 
